name: Build OpenJDK 25 for Android

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_android:
    strategy:
      matrix:
        arch: [ "aarch32", "aarch64", "x86_64" ]
      fail-fast: false

    name: "Build for Android ${{matrix.arch}}"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build with CI build script
      run: bash "ci_build_arch_${{matrix.arch}}.sh"

    - name: Upload JRE build output
      uses: actions/upload-artifact@v4
      with:
        name: 'jre25-${{matrix.arch}}'
        path: jre25*.tar.xz

  fcl:
    needs: build_android
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get jre25-aarch32
      uses: actions/download-artifact@v4
      with:
        name: jre25-aarch32
        path: fcl

    - name: Get jre25-aarch64
      uses: actions/download-artifact@v4
      with:
        name: jre25-aarch64
        path: fcl

    - name: Get jre25-x86_64
      uses: actions/download-artifact@v4
      with:
        name: jre25-x86_64
        path: fcl

    - name: Repack JRE
      run: bash "repack_jre.sh" $GITHUB_WORKSPACE/fcl $GITHUB_WORKSPACE/fcl/jre25-multiarch

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: jre25-multiarch
          path: fcl/jre25-multiarch/*
